Feat/multiple felts
starknet-id/contract pull request #8
Opened 2023-02-08 08:56 UTC by Th0rgal

This pull request introduces multiple felts support to the StarknetID contract.

It relies on the storage_write and storage_read syscalls. It will find the address of a single felt variable and allow writing multiple felts after it. It also adds multiple functions to help reading multiple felts.

2023-02-08 13:09 UTC, 0xBenaparte requested changes
Quelques questions + demandes de refactor sur les tests.

2023-02-08 13:09 UTC, fricoben commented on src/IStarknetID.cairo
> +        data_len: felt, data: felt*
Pourquoi a t-on deux fonctions différentes ici ? On a pas la length ? Je ne trouve pas `get_extended_unknown_user_data` dans le code, cela correspond à quoi ?

2023-02-08 13:09 UTC, 0xBenaparte commented on tests/test_extended_data.cairo
> +    set_extended_verifier_data(token_id, 'avatar', 2, new (12345, 6789));
Comment : Should ...

2023-02-08 13:09 UTC, 0xBenaparte commented on tests/test_extended_data.cairo
> +    let (len, values) = get_unbounded_verifier_data(token_id, 'avatar', 123);
Unbounded en gros ça get la verifier data peu importe si c'est extended ou pas c'est ça ?

2023-02-08 13:09 UTC, 0xBenaparte commented on tests/test_extended_data.cairo
> +    let (len, values) = get_unbounded_verifier_data(token_id, 'yolo', 123);
Should ...

2023-02-08 13:09 UTC, 0xBenaparte commented on src/storage.cairo
> +// lemgth should be zero at first
length*

2023-02-08 13:09 UTC, 0xBenaparte commented on src/IStarknetID.cairo
> -    func get_confirmed_data(starknet_id: felt, field: felt, address: felt) -> (data: felt) {
get_confirmed_data sera donc à changer dans le front et à chaque fois ou quelqu'un l'utilise ?

2023-02-08 13:09 UTC, 0xBenaparte commented on tests/test_extended_data.cairo
> +}
Tu n'as pas testé toutes la parties user ? Ca doit etre assez facile !

2023-02-09 08:24 UTC, Th0rgal commented on src/IStarknetID.cairo
> +        data_len: felt, data: felt*
bien vu, j'ai oublié de la renommer en get_unbounded

2023-02-09 08:24 UTC, Th0rgal commented on tests/test_extended_data.cairo
> +    let (len, values) = get_unbounded_verifier_data(token_id, 'avatar', 123);
Non, ça récupère jusqu'à trouver zéro, tu ne spécifies pas la taille (la bound)

2023-02-09 08:25 UTC, Th0rgal commented on tests/test_extended_data.cairo
> +}
Effectivement, je vais ajouter du coverage

2023-02-09 08:35 UTC, Th0rgal commented on src/IStarknetID.cairo
> -    func get_confirmed_data(starknet_id: felt, field: felt, address: felt) -> (data: felt) {
J'ai décidé de l'enlever car elle n'est pas utilisée

2023-02-10 10:21 UTC, 0xBenaparte approved these changes

2023-02-10 10:21 UTC, merged